import type { State, StepType } from './types';

export const STORAGE_KEY = 'beekle-flow-mapper-v2';
export const ONBOARDING_KEY = 'beekle-flow-mapper-onboarding-dismissed';

export const STEP_TYPE_LABEL: Record<StepType, string> = {
  start: '開始',
  task: '作業',
  decision: '判断',
  system: 'システム',
  wait: '待ち',
  end: '完了',
};

export const STEP_TYPE_STYLE: Record<StepType, string> = {
  start: 'bg-emerald-100 border-emerald-500 text-emerald-900',
  task: 'bg-white border-gray-400 text-gray-900',
  decision: 'bg-amber-100 border-amber-500 text-amber-900',
  system: 'bg-sky-100 border-sky-500 text-sky-900',
  wait: 'bg-gray-100 border-gray-400 text-gray-700',
  end: 'bg-rose-100 border-rose-500 text-rose-900',
};

export const STEP_TYPE_FILL: Record<StepType, string> = {
  start: '#d1fae5',
  task: '#ffffff',
  decision: '#fef3c7',
  system: '#e0f2fe',
  wait: '#f3f4f6',
  end: '#ffe4e6',
};

export const STEP_TYPE_STROKE: Record<StepType, string> = {
  start: '#10b981',
  task: '#9ca3af',
  decision: '#f59e0b',
  system: '#0ea5e9',
  wait: '#9ca3af',
  end: '#f43f5e',
};

export const SUGGESTION_BADGE: Record<
  'automation' | 'ai' | 'parallel' | 'priority' | 'tool',
  { label: string; color: string }
> = {
  automation: {
    label: '自動化',
    color: 'bg-secondary-100 text-secondary-900 border-secondary-300',
  },
  ai: { label: 'AI適用', color: 'bg-primary-100 text-primary-900 border-primary-300' },
  parallel: { label: '並行化', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  priority: { label: '重点改善', color: 'bg-rose-100 text-rose-900 border-rose-300' },
  tool: { label: 'ツール選定', color: 'bg-amber-100 text-amber-900 border-amber-300' },
};

// レイアウト寸法（PX）
export const CARD_W = 180;
export const CARD_H = 72;
export const CARD_GAP = 12;
export const PHASE_PAD_X = 24;
export const LANE_PAD_Y = 16;
export const HEADER_H = 48;
export const LANE_LABEL_W = 120;

export const EMPTY: State = {
  asIs: {
    title: '現状の業務フロー',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②処理' },
      { id: 'p3', name: '③完了' },
    ],
    lanes: [{ id: 'l1', name: '担当者A' }],
    steps: [],
  },
  toBe: {
    title: '改善後の業務フロー',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②処理' },
      { id: 'p3', name: '③完了' },
    ],
    lanes: [{ id: 'l1', name: '担当者A' }],
    steps: [],
  },
};

export const SAMPLE: State = {
  asIs: {
    title: '受注〜出荷業務（紙・電話運用）',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②引当・指示' },
      { id: 'p3', name: '③出荷' },
    ],
    lanes: [
      { id: 'l1', name: '顧客', rateYenPerHour: 0 },
      { id: 'l2', name: '営業担当', rateYenPerHour: 4500 },
      { id: 'l3', name: '事務', rateYenPerHour: 3000 },
      { id: 'l4', name: '倉庫', rateYenPerHour: 2800 },
    ],
    steps: [
      {
        id: 's1',
        type: 'start',
        laneId: 'l1',
        phaseId: 'p1',
        label: 'メール／FAXで注文',
        durationMin: 0,
        tool: 'メール／FAX',
        pain: '',
        improvement: '',
        next: ['s2'],
      },
      {
        id: 's2',
        type: 'task',
        laneId: 'l2',
        phaseId: 'p1',
        label: '営業がExcelに転記',
        durationMin: 15,
        tool: 'Excel',
        pain: '転記ミスが月3〜5件',
        improvement: '',
        next: ['s3'],
      },
      {
        id: 's3',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p2',
        label: '事務が在庫を電話で確認',
        durationMin: 20,
        tool: '電話',
        pain: '倉庫が忙しいと折返し待ち',
        improvement: '',
        next: ['s4'],
      },
      {
        id: 's4',
        type: 'decision',
        laneId: 'l3',
        phaseId: 'p2',
        label: '在庫あり？',
        durationMin: 5,
        tool: '',
        pain: '',
        improvement: '',
        next: ['s5', 's9'],
      },
      {
        id: 's5',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p2',
        label: '注文書を紙で印刷',
        durationMin: 10,
        tool: 'プリンタ',
        pain: '紙の行き来で半日ロス',
        improvement: '',
        next: ['s6'],
      },
      {
        id: 's6',
        type: 'task',
        laneId: 'l4',
        phaseId: 'p3',
        label: 'ピッキング・梱包',
        durationMin: 60,
        tool: '紙の指示書',
        pain: '指示書の紛失あり',
        improvement: '',
        next: ['s7'],
      },
      {
        id: 's7',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p3',
        label: '送り状を手書き',
        durationMin: 15,
        tool: 'ペン／伝票',
        pain: '宛名ミス',
        improvement: '',
        next: ['s8'],
      },
      {
        id: 's8',
        type: 'end',
        laneId: 'l4',
        phaseId: 'p3',
        label: '集荷・出荷',
        durationMin: 10,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
      {
        id: 's9',
        type: 'task',
        laneId: 'l2',
        phaseId: 'p2',
        label: '営業が顧客に納期回答',
        durationMin: 20,
        tool: '電話',
        pain: '謝罪対応が常態化',
        improvement: '',
        next: ['s10'],
      },
      {
        id: 's10',
        type: 'end',
        laneId: 'l1',
        phaseId: 'p2',
        label: '欠品連絡（注文取消）',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
    ],
  },
  toBe: {
    title: '受注〜出荷業務（システム化後）',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②引当・指示' },
      { id: 'p3', name: '③出荷' },
    ],
    lanes: [
      { id: 'l1', name: '顧客', rateYenPerHour: 0 },
      { id: 'l2', name: '営業担当', rateYenPerHour: 4500 },
      { id: 'l3', name: '事務', rateYenPerHour: 3000 },
      { id: 'l4', name: '倉庫', rateYenPerHour: 2800 },
      { id: 'l5', name: 'システム', rateYenPerHour: 0 },
    ],
    steps: [
      {
        id: 's1',
        type: 'start',
        laneId: 'l1',
        phaseId: 'p1',
        label: 'Webフォームで注文',
        durationMin: 0,
        tool: '受注Webフォーム',
        pain: '',
        improvement: '入力規則で誤注文を未然防止',
        next: ['s2'],
      },
      {
        id: 's2',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: '在庫を自動引当',
        durationMin: 0,
        tool: '在庫API',
        pain: '',
        improvement: '電話確認を撤廃',
        next: ['s3'],
      },
      {
        id: 's3',
        type: 'decision',
        laneId: 'l5',
        phaseId: 'p2',
        label: '在庫あり？',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '',
        next: ['s4', 's8'],
      },
      {
        id: 's4',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: 'ピッキング指示を自動生成',
        durationMin: 0,
        tool: 'WMS',
        pain: '',
        improvement: '紙の指示書を廃止',
        next: ['s5'],
      },
      {
        id: 's5',
        type: 'task',
        laneId: 'l4',
        phaseId: 'p3',
        label: 'ハンディでピッキング',
        durationMin: 40,
        tool: 'ハンディ端末',
        pain: '',
        improvement: '誤出荷をリアルタイム検知',
        next: ['s6'],
      },
      {
        id: 's6',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p3',
        label: '送り状を自動発行',
        durationMin: 0,
        tool: '配送API',
        pain: '',
        improvement: '宛名ミスを撲滅',
        next: ['s7'],
      },
      {
        id: 's7',
        type: 'end',
        laneId: 'l4',
        phaseId: 'p3',
        label: '集荷・出荷',
        durationMin: 5,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
      {
        id: 's8',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: '欠品を即座に通知',
        durationMin: 0,
        tool: 'メール／LINE',
        pain: '',
        improvement: '営業の電話謝罪を不要化',
        next: ['s9'],
      },
      {
        id: 's9',
        type: 'end',
        laneId: 'l1',
        phaseId: 'p2',
        label: '代替提案を確認',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '機会損失を抑制',
        next: [],
      },
    ],
  },
};
