import type { FlowDiagram, State, StepType } from './types';

export const STORAGE_KEY = 'beekle-flow-mapper-v2';
export const ONBOARDING_KEY = 'beekle-flow-mapper-onboarding-dismissed';

export const STEP_TYPE_LABEL: Record<StepType, string> = {
  start: '開始',
  task: '作業',
  decision: '判断',
  system: 'システム',
  wait: '待ち',
  end: '完了',
};

export const STEP_TYPE_STYLE: Record<StepType, string> = {
  start: 'bg-emerald-100 border-emerald-500 text-emerald-900',
  task: 'bg-white border-gray-400 text-gray-900',
  decision: 'bg-amber-100 border-amber-500 text-amber-900',
  system: 'bg-sky-100 border-sky-500 text-sky-900',
  wait: 'bg-gray-100 border-gray-400 text-gray-700',
  end: 'bg-rose-100 border-rose-500 text-rose-900',
};

export const STEP_TYPE_FILL: Record<StepType, string> = {
  start: '#d1fae5',
  task: '#ffffff',
  decision: '#fef3c7',
  system: '#e0f2fe',
  wait: '#f3f4f6',
  end: '#ffe4e6',
};

export const STEP_TYPE_STROKE: Record<StepType, string> = {
  start: '#10b981',
  task: '#9ca3af',
  decision: '#f59e0b',
  system: '#0ea5e9',
  wait: '#9ca3af',
  end: '#f43f5e',
};

export const SUGGESTION_BADGE: Record<
  'automation' | 'ai' | 'parallel' | 'priority' | 'tool',
  { label: string; color: string }
> = {
  automation: {
    label: '自動化',
    color: 'bg-secondary-100 text-secondary-900 border-secondary-300',
  },
  ai: { label: 'AI適用', color: 'bg-primary-100 text-primary-900 border-primary-300' },
  parallel: { label: '並行化', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  priority: { label: '重点改善', color: 'bg-rose-100 text-rose-900 border-rose-300' },
  tool: { label: 'ツール選定', color: 'bg-amber-100 text-amber-900 border-amber-300' },
};

// レイアウト寸法（PX）
export const CARD_W = 180;
export const CARD_H = 72;
export const CARD_GAP = 12;
export const PHASE_PAD_X = 24;
export const LANE_PAD_Y = 16;
export const HEADER_H = 48;
export const LANE_LABEL_W = 120;

export const EMPTY: State = {
  asIs: {
    title: '現状の業務フロー',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②処理' },
      { id: 'p3', name: '③完了' },
    ],
    lanes: [{ id: 'l1', name: '担当者A' }],
    steps: [],
  },
  toBe: {
    title: '改善後の業務フロー',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②処理' },
      { id: 'p3', name: '③完了' },
    ],
    lanes: [{ id: 'l1', name: '担当者A' }],
    steps: [],
  },
};

export const SAMPLE: State = {
  asIs: {
    title: '受注〜出荷業務（紙・電話運用）',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②引当・指示' },
      { id: 'p3', name: '③出荷' },
    ],
    lanes: [
      { id: 'l1', name: '顧客', rateYenPerHour: 0 },
      { id: 'l2', name: '営業担当', rateYenPerHour: 4500 },
      { id: 'l3', name: '事務', rateYenPerHour: 3000 },
      { id: 'l4', name: '倉庫', rateYenPerHour: 2800 },
    ],
    steps: [
      {
        id: 's1',
        type: 'start',
        laneId: 'l1',
        phaseId: 'p1',
        label: 'メール／FAXで注文',
        durationMin: 0,
        tool: 'メール／FAX',
        pain: '',
        improvement: '',
        next: ['s2'],
      },
      {
        id: 's2',
        type: 'task',
        laneId: 'l2',
        phaseId: 'p1',
        label: '営業がExcelに転記',
        durationMin: 15,
        tool: 'Excel',
        pain: '転記ミスが月3〜5件',
        improvement: '',
        next: ['s3'],
      },
      {
        id: 's3',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p2',
        label: '事務が在庫を電話で確認',
        durationMin: 20,
        tool: '電話',
        pain: '倉庫が忙しいと折返し待ち',
        improvement: '',
        next: ['s4'],
      },
      {
        id: 's4',
        type: 'decision',
        laneId: 'l3',
        phaseId: 'p2',
        label: '在庫あり？',
        durationMin: 5,
        tool: '',
        pain: '',
        improvement: '',
        next: ['s5', 's9'],
      },
      {
        id: 's5',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p2',
        label: '注文書を紙で印刷',
        durationMin: 10,
        tool: 'プリンタ',
        pain: '紙の行き来で半日ロス',
        improvement: '',
        next: ['s6'],
      },
      {
        id: 's6',
        type: 'task',
        laneId: 'l4',
        phaseId: 'p3',
        label: 'ピッキング・梱包',
        durationMin: 60,
        tool: '紙の指示書',
        pain: '指示書の紛失あり',
        improvement: '',
        next: ['s7'],
      },
      {
        id: 's7',
        type: 'task',
        laneId: 'l3',
        phaseId: 'p3',
        label: '送り状を手書き',
        durationMin: 15,
        tool: 'ペン／伝票',
        pain: '宛名ミス',
        improvement: '',
        next: ['s8'],
      },
      {
        id: 's8',
        type: 'end',
        laneId: 'l4',
        phaseId: 'p3',
        label: '集荷・出荷',
        durationMin: 10,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
      {
        id: 's9',
        type: 'task',
        laneId: 'l2',
        phaseId: 'p2',
        label: '営業が顧客に納期回答',
        durationMin: 20,
        tool: '電話',
        pain: '謝罪対応が常態化',
        improvement: '',
        next: ['s10'],
      },
      {
        id: 's10',
        type: 'end',
        laneId: 'l1',
        phaseId: 'p2',
        label: '欠品連絡（注文取消）',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
    ],
  },
  toBe: {
    title: '受注〜出荷業務（システム化後）',
    phases: [
      { id: 'p1', name: '①受注' },
      { id: 'p2', name: '②引当・指示' },
      { id: 'p3', name: '③出荷' },
    ],
    lanes: [
      { id: 'l1', name: '顧客', rateYenPerHour: 0 },
      { id: 'l2', name: '営業担当', rateYenPerHour: 4500 },
      { id: 'l3', name: '事務', rateYenPerHour: 3000 },
      { id: 'l4', name: '倉庫', rateYenPerHour: 2800 },
      { id: 'l5', name: 'システム', rateYenPerHour: 0 },
    ],
    steps: [
      {
        id: 's1',
        type: 'start',
        laneId: 'l1',
        phaseId: 'p1',
        label: 'Webフォームで注文',
        durationMin: 0,
        tool: '受注Webフォーム',
        pain: '',
        improvement: '入力規則で誤注文を未然防止',
        next: ['s2'],
      },
      {
        id: 's2',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: '在庫を自動引当',
        durationMin: 0,
        tool: '在庫API',
        pain: '',
        improvement: '電話確認を撤廃',
        next: ['s3'],
      },
      {
        id: 's3',
        type: 'decision',
        laneId: 'l5',
        phaseId: 'p2',
        label: '在庫あり？',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '',
        next: ['s4', 's8'],
      },
      {
        id: 's4',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: 'ピッキング指示を自動生成',
        durationMin: 0,
        tool: 'WMS',
        pain: '',
        improvement: '紙の指示書を廃止',
        next: ['s5'],
      },
      {
        id: 's5',
        type: 'task',
        laneId: 'l4',
        phaseId: 'p3',
        label: 'ハンディでピッキング',
        durationMin: 40,
        tool: 'ハンディ端末',
        pain: '',
        improvement: '誤出荷をリアルタイム検知',
        next: ['s6'],
      },
      {
        id: 's6',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p3',
        label: '送り状を自動発行',
        durationMin: 0,
        tool: '配送API',
        pain: '',
        improvement: '宛名ミスを撲滅',
        next: ['s7'],
      },
      {
        id: 's7',
        type: 'end',
        laneId: 'l4',
        phaseId: 'p3',
        label: '集荷・出荷',
        durationMin: 5,
        tool: '',
        pain: '',
        improvement: '',
        next: [],
      },
      {
        id: 's8',
        type: 'system',
        laneId: 'l5',
        phaseId: 'p2',
        label: '欠品を即座に通知',
        durationMin: 0,
        tool: 'メール／LINE',
        pain: '',
        improvement: '営業の電話謝罪を不要化',
        next: ['s9'],
      },
      {
        id: 's9',
        type: 'end',
        laneId: 'l1',
        phaseId: 'p2',
        label: '代替提案を確認',
        durationMin: 0,
        tool: '',
        pain: '',
        improvement: '機会損失を抑制',
        next: [],
      },
    ],
  },
};

// 業種別テンプレート。初回起動時の白紙キャンバス回避のため、
// 典型的な日本企業のフローを 5 種類用意する。クリックで As-Is に流し込む。
// id は静的だが、store の loadTemplate で deep clone するので衝突しない。
export type FlowTemplate = {
  id: string;
  name: string;
  description: string;
  diagram: FlowDiagram;
};

export const TEMPLATES: FlowTemplate[] = [
  {
    id: 'order-shipping',
    name: '受注〜出荷（紙・電話運用）',
    description: '営業→事務→倉庫の典型フロー。Excel転記・電話確認・紙の指示書による業務。',
    diagram: SAMPLE.asIs,
  },
  {
    id: 'expense',
    name: '経費精算',
    description: '紙の領収書とハンコ押印を伴う、月末集中型の精算フロー。',
    diagram: {
      title: '経費精算（紙・押印運用）',
      phases: [
        { id: 'p1', name: '①申請' },
        { id: 'p2', name: '②承認' },
        { id: 'p3', name: '③精算' },
      ],
      lanes: [
        { id: 'l1', name: '申請者', rateYenPerHour: 4000 },
        { id: 'l2', name: '上長', rateYenPerHour: 6000 },
        { id: 'l3', name: '経理', rateYenPerHour: 3500 },
      ],
      steps: [
        {
          id: 'expense-s1',
          type: 'start',
          laneId: 'l1',
          phaseId: 'p1',
          label: '領収書を受領',
          durationMin: 0,
          tool: '紙の領収書',
          pain: '',
          improvement: '',
          next: ['expense-s2'],
        },
        {
          id: 'expense-s2',
          type: 'task',
          laneId: 'l1',
          phaseId: 'p1',
          label: 'Excelに入力・申請書作成',
          durationMin: 30,
          tool: 'Excel',
          pain: '月末に集中して2日かかる',
          improvement: '',
          next: ['expense-s3'],
        },
        {
          id: 'expense-s3',
          type: 'task',
          laneId: 'l1',
          phaseId: 'p1',
          label: '印刷・押印・社内便で送付',
          durationMin: 15,
          tool: 'プリンタ／印鑑',
          pain: '領収書紛失リスク',
          improvement: '',
          next: ['expense-s4'],
        },
        {
          id: 'expense-s4',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p2',
          label: '上長が内容確認・承認印',
          durationMin: 10,
          tool: '印鑑',
          pain: '上長不在で承認止まり',
          improvement: '',
          next: ['expense-s5'],
        },
        {
          id: 'expense-s5',
          type: 'decision',
          laneId: 'l3',
          phaseId: 'p3',
          label: '内容OK？',
          durationMin: 10,
          tool: '',
          pain: '',
          improvement: '',
          next: ['expense-s6', 'expense-s8'],
        },
        {
          id: 'expense-s6',
          type: 'task',
          laneId: 'l3',
          phaseId: 'p3',
          label: '会計仕訳・振込データ作成',
          durationMin: 20,
          tool: '会計ソフト',
          pain: '勘定科目の判断に都度迷う',
          improvement: '',
          next: ['expense-s7'],
        },
        {
          id: 'expense-s7',
          type: 'end',
          laneId: 'l3',
          phaseId: 'p3',
          label: '振込完了',
          durationMin: 5,
          tool: '銀行振込',
          pain: '',
          improvement: '',
          next: [],
        },
        {
          id: 'expense-s8',
          type: 'end',
          laneId: 'l1',
          phaseId: 'p3',
          label: '差戻し（再申請）',
          durationMin: 0,
          tool: '',
          pain: '差戻し率が高く再作業が発生',
          improvement: '',
          next: [],
        },
      ],
    },
  },
  {
    id: 'recruiting',
    name: '採用面接',
    description: '応募〜内定までの典型フロー。日程調整のメール往復に時間がかかる。',
    diagram: {
      title: '採用面接（中途採用）',
      phases: [
        { id: 'p1', name: '①応募' },
        { id: 'p2', name: '②書類選考' },
        { id: 'p3', name: '③面接' },
        { id: 'p4', name: '④内定' },
      ],
      lanes: [
        { id: 'l1', name: '候補者', rateYenPerHour: 0 },
        { id: 'l2', name: '採用担当', rateYenPerHour: 4000 },
        { id: 'l3', name: '現場マネージャー', rateYenPerHour: 6500 },
        { id: 'l4', name: '経営', rateYenPerHour: 9000 },
      ],
      steps: [
        {
          id: 'rec-s1',
          type: 'start',
          laneId: 'l1',
          phaseId: 'p1',
          label: '求人媒体から応募',
          durationMin: 0,
          tool: '求人サイト',
          pain: '',
          improvement: '',
          next: ['rec-s2'],
        },
        {
          id: 'rec-s2',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p1',
          label: '応募受付・スプレッドシート登録',
          durationMin: 15,
          tool: 'Googleスプレッドシート',
          pain: '媒体ごとの形式バラバラ',
          improvement: '',
          next: ['rec-s3'],
        },
        {
          id: 'rec-s3',
          type: 'task',
          laneId: 'l3',
          phaseId: 'p2',
          label: '書類確認・1次合否判断',
          durationMin: 30,
          tool: 'PDF閲覧',
          pain: '判断基準が属人的',
          improvement: '',
          next: ['rec-s4'],
        },
        {
          id: 'rec-s4',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p3',
          label: '一次面接の日程調整',
          durationMin: 45,
          tool: 'メール',
          pain: 'メール往復で平均5往復',
          improvement: '',
          next: ['rec-s5'],
        },
        {
          id: 'rec-s5',
          type: 'task',
          laneId: 'l3',
          phaseId: 'p3',
          label: '一次面接実施・評価記入',
          durationMin: 75,
          tool: 'Web会議／評価シート',
          pain: '評価シートの提出遅延',
          improvement: '',
          next: ['rec-s6'],
        },
        {
          id: 'rec-s6',
          type: 'task',
          laneId: 'l4',
          phaseId: 'p3',
          label: '二次面接（経営）',
          durationMin: 60,
          tool: 'Web会議',
          pain: '経営の予定が取りにくい',
          improvement: '',
          next: ['rec-s7'],
        },
        {
          id: 'rec-s7',
          type: 'end',
          laneId: 'l2',
          phaseId: 'p4',
          label: '内定通知（電話＋書面）',
          durationMin: 30,
          tool: '電話／郵送',
          pain: '',
          improvement: '',
          next: [],
        },
      ],
    },
  },
  {
    id: 'inquiry',
    name: '問い合わせ対応',
    description: '一次受付から専門担当への引き継ぎ、回答までのカスタマーサポートフロー。',
    diagram: {
      title: '問い合わせ対応（一次／二次切り分け）',
      phases: [
        { id: 'p1', name: '①受付' },
        { id: 'p2', name: '②調査' },
        { id: 'p3', name: '③回答' },
      ],
      lanes: [
        { id: 'l1', name: '顧客', rateYenPerHour: 0 },
        { id: 'l2', name: '一次対応', rateYenPerHour: 3000 },
        { id: 'l3', name: '専門担当', rateYenPerHour: 5500 },
      ],
      steps: [
        {
          id: 'inq-s1',
          type: 'start',
          laneId: 'l1',
          phaseId: 'p1',
          label: 'フォーム／電話で問い合わせ',
          durationMin: 0,
          tool: 'フォーム／電話',
          pain: '',
          improvement: '',
          next: ['inq-s2'],
        },
        {
          id: 'inq-s2',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p1',
          label: 'チケット化・分類',
          durationMin: 10,
          tool: 'Excel／Backlog',
          pain: '分類ルールが属人化',
          improvement: '',
          next: ['inq-s3'],
        },
        {
          id: 'inq-s3',
          type: 'decision',
          laneId: 'l2',
          phaseId: 'p1',
          label: '一次で答えられる？',
          durationMin: 5,
          tool: '',
          pain: '',
          improvement: '',
          next: ['inq-s4', 'inq-s5'],
        },
        {
          id: 'inq-s4',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p3',
          label: 'FAQから回答案作成',
          durationMin: 15,
          tool: 'FAQドキュメント',
          pain: 'FAQの更新が追いつかない',
          improvement: '',
          next: ['inq-s7'],
        },
        {
          id: 'inq-s5',
          type: 'task',
          laneId: 'l3',
          phaseId: 'p2',
          label: '専門担当が過去事例を検索・調査',
          durationMin: 45,
          tool: '社内Wiki',
          pain: '過去事例の検索性が低い',
          improvement: '',
          next: ['inq-s6'],
        },
        {
          id: 'inq-s6',
          type: 'task',
          laneId: 'l3',
          phaseId: 'p3',
          label: '回答案を作成・上長確認',
          durationMin: 30,
          tool: 'Word／メール',
          pain: '上長確認待ちで翌日対応',
          improvement: '',
          next: ['inq-s7'],
        },
        {
          id: 'inq-s7',
          type: 'end',
          laneId: 'l2',
          phaseId: 'p3',
          label: '顧客へメール返信',
          durationMin: 10,
          tool: 'メール',
          pain: '',
          improvement: '',
          next: [],
        },
      ],
    },
  },
  {
    id: 'invoicing',
    name: '月次請求書発行',
    description: '営業→経理→顧客の典型サイクル。Excel集計とPDFメール送付。',
    diagram: {
      title: '月次請求書発行（Excel運用）',
      phases: [
        { id: 'p1', name: '①締め' },
        { id: 'p2', name: '②計算' },
        { id: 'p3', name: '③発行' },
      ],
      lanes: [
        { id: 'l1', name: '営業', rateYenPerHour: 4500 },
        { id: 'l2', name: '経理', rateYenPerHour: 3500 },
        { id: 'l3', name: '顧客', rateYenPerHour: 0 },
      ],
      steps: [
        {
          id: 'inv-s1',
          type: 'start',
          laneId: 'l1',
          phaseId: 'p1',
          label: '月次データを集計（営業）',
          durationMin: 60,
          tool: 'Excel',
          pain: '日報の入力漏れ確認に時間',
          improvement: '',
          next: ['inv-s2'],
        },
        {
          id: 'inv-s2',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p2',
          label: '請求金額を計算',
          durationMin: 45,
          tool: 'Excel',
          pain: '関数のメンテに依存',
          improvement: '',
          next: ['inv-s3'],
        },
        {
          id: 'inv-s3',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p2',
          label: '請求書テンプレに転記',
          durationMin: 30,
          tool: 'Word／Excel',
          pain: '転記ミスが月1〜2件',
          improvement: '',
          next: ['inv-s4'],
        },
        {
          id: 'inv-s4',
          type: 'task',
          laneId: 'l1',
          phaseId: 'p2',
          label: '営業が内容確認・承認',
          durationMin: 15,
          tool: 'メール',
          pain: '営業の確認待ち',
          improvement: '',
          next: ['inv-s5'],
        },
        {
          id: 'inv-s5',
          type: 'task',
          laneId: 'l2',
          phaseId: 'p3',
          label: 'PDF化・メール送付',
          durationMin: 20,
          tool: 'Acrobat／Outlook',
          pain: '宛先の取り違え',
          improvement: '',
          next: ['inv-s6'],
        },
        {
          id: 'inv-s6',
          type: 'wait',
          laneId: 'l3',
          phaseId: 'p3',
          label: '入金待ち',
          durationMin: 0,
          tool: '',
          pain: '入金遅延の督促が発生',
          improvement: '',
          next: ['inv-s7'],
        },
        {
          id: 'inv-s7',
          type: 'end',
          laneId: 'l2',
          phaseId: 'p3',
          label: '入金確認・消込',
          durationMin: 15,
          tool: '銀行明細／会計ソフト',
          pain: '',
          improvement: '',
          next: [],
        },
      ],
    },
  },
];
